### ISSUE TITLE
Atualização do projeto

### ISSUE THREAD

**Issue by JoseRFJuniorLLMs** [m4rciosouza/ponto-inteligente-client-curso-angular#1]
Professor Márcio, ao tentar migrar o projeto para Angular 6 estou pegando, um erro já fez essa atualização ?

{
  "name": "ponto-inteligente",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve --proxy-config proxy.conf.json --aot",
    "build": "ng build --prod",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^6.0.7",
    "@angular/cdk": "^6.3.2",
    "@angular/common": "^6.0.7",
    "@angular/compiler": "^6.0.7",
    "@angular/core": "^6.0.7",
    "@angular/flex-layout": "^6.0.0-beta.16",
    "@angular/forms": "^6.0.7",
    "@angular/http": "^6.0.7",
    "@angular/material": "^6.3.2",
    "@angular/platform-browser": "^6.0.7",
    "@angular/platform-browser-dynamic": "^6.0.7",
    "@angular/router": "^6.0.7",
    "core-js": "^2.5.7",
    "hammerjs": "^2.0.8",
    "moment": "^2.22.2",
    "rxjs": "^6.2.1",
    "zone.js": "^0.8.26"
  },
  "devDependencies": {
    "@angular/cli": "6.0.8",
    "@angular/compiler-cli": "^6.0.7",
    "@angular/language-service": "^6.0.7",
    "@types/jasmine": "~2.8.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~10.5.2",
    "codelyzer": "^4.4.2",
    "jasmine-core": "~3.1.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~2.0.4",
    "karma-chrome-launcher": "~2.2.0",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^2.0.1",
    "karma-jasmine": "~1.1.2",
    "karma-jasmine-html-reporter": "^1.2.0",
    "protractor": "~5.3.2",
    "ts-node": "~7.0.0",
    "tslint": "~5.10.0",
    "typescript": "~2.7.2"
  }
}

ng serve
Local workspace file ('angular.json') could not be found.
Error: Local workspace file ('angular.json') could not be found.
    at WorkspaceLoader._getProjectWorkspaceFilePath (/home/dev/Documentos/ANGULAR-TUDO/ponto-inteligente-client-curso-angular/node_modules/@angular/cli/models/workspace-loader.js:37:19)
    at WorkspaceLoader.loadWorkspace (/home/dev/Documentos/ANGULAR-TUDO/ponto-inteligente-client-curso-angular/node_modules/@angular/cli/models/workspace-loader.js:24:21)
    at ServeCommand._loadWorkspaceAndArchitect (/home/dev/Documentos/ANGULAR-TUDO/ponto-inteligente-client-curso-angular/node_modules/@angular/cli/models/architect-command.js:180:32)
    at ServeCommand.<anonymous> (/home/dev/Documentos/ANGULAR-TUDO/ponto-inteligente-client-curso-angular/node_modules/@angular/cli/models/architect-command.js:47:25)
    at Generator.next (<anonymous>)
    at /home/dev/Documentos/ANGULAR-TUDO/ponto-inteligente-client-curso-angular/node_modules/@angular/cli/models/architect-command.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/home/dev/Documentos/ANGULAR-TUDO/ponto-inteligente-client-curso-angular/node_modules/@angular/cli/models/architect-command.js:3:12)
    at ServeCommand.initialize (/home/dev/Documentos/ANGULAR-TUDO/ponto-inteligente-client-curso-angular/node_modules/@angular/cli/models/architect-command.js:46:16)
    at Object.<anonymous> (/home/dev/Documentos/ANGULAR-TUDO/ponto-inteligente-client-curso-angular/node_modules/@angular/cli/models/command-runner.js:87:23)

**Comment by m4rciosouza** [comment]
Olá,

o Angular 6 modificou o nome do arquivo de configuração principal para angular.json, assim é preciso executar algumas etapas para fazer a atualização.
No site oficial https://update.angular.io você pode selecionar a versão atual do projeto que ele exibirá os detalhes e passos para atualizar para a versão 6.
